# Generated by Django 5.0.2 on 2024-02-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('cat', models.CharField(max_length=2)),
                ('from_value', models.FloatField()),
                ('to_value', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
